apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  namespace: dev
  labels:
    app: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-app
        image: afreen20/login-app
        ports:
        - containerPort: 80



