apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: login-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

